### ISSUE TITLE
Multiple attributes

### ISSUE THREAD

**Issue by gczh** [ankane/neighbor#10]
Is there anyway to support multiple attributes?

For instance, a model may have `embeddings` and `factors`, both of which are used for different purposes. Is there any way then to do something like

```ruby
class SomeModel < ApplicationRecord
  has_neighbors :embeddings, :factors
  
   ...
end
```

**Comment by gczh** [comment]
Solved this by doing the following:

```ruby
class SomeModel < ApplicationRecord
  has_neighbors :embeddings, :factors
  has_neighbors :factors
  
   ...
end
```

@ankane Although, it'll be nice if we could do something like in the original question. That would be more intuitive!

Thank you so much for making this tool that greatly contributes to Ruby's ML ecosystem!

PS: If it's not too much to ask here, @ankane, is there any way to use Disco to generate factors in almost real-time (when there is new data, update the model) Would that be expensive resource-wise?

**Comment by ankane** [comment]
Hi @gczh, thanks for the suggestion. Added support for passing multiple attributes in a single call in the commit above.

Re Disco: the current matrix factorization library doesn't support it (https://github.com/ankane/disco/issues/24).
