### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by danielfriis** [ankane/neighbor#17]
This might not be the right place to ask this question, in which case, feel free to close the issue!

I'm using neighbor to build a RAG system using a vector db (pgvector).

I have a bunch of very different documents where I need to find an answer, but I struggle to retrieve the correct chunk.

Are there any best practices for making the results better?

**Comment by ankane** [comment]
Hi @danielfriis, the nearest neighbor search should have 100% accuracy if there's not an approximate index. I'd double check the query is correct (if you have a `default_scope` on the model, it'll take precedence until 0.4.0) as well as the distance function (you'll typically want to use `cosine`). For general best practices for RAG, it'd be better to use other resources.

**Comment by danielfriis** [comment]
@ankane thanks a lot. That makes 100p sense!
