### ISSUE TITLE
Is there a way to suppress the logs of the embedding column?

### ISSUE THREAD

**Issue by fangherk** [ankane/neighbor#18]
Sometimes in development, seeing the vectors is pretty unwieldy and it makes it hard to debug other queries that are happening. To address this, I use `ActiveRecord::Base.logger.silence`. For example, for a set of Document Activerecord objects, I write something like this:
```
  def closest_documents(vector)
      ActiveRecord::Base.logger.silence do
        Document
          .where(company_id: id)
          .nearest_neighbors(:embedding, vector, distance: "cosine")
          .first(5)
      end
  end
```  

I'm curious if other people have recommended solutions or ideas to hide the output.

**Comment by ankane** [comment]
Hi @fangherk, that's probably the best way (I'm not aware of a way to suppress just the vector).

**Comment by chalmagean** [comment]
You could also use:

`ActiveRecord::Base.filter_attributes = [:embedding]`
