### ISSUE TITLE
Dimension Validation

### ISSUE THREAD

**Issue by moracca** [ankane/neighbor#19]
When we create a vector column we specify the number of dimensions, and this should match the number of dimensions being generated by the embedding model.  If we attempt to insert an embedding with the wrong number of dimensions, we get an error `Neighbor::Error: Expected X dimensions, not Y`.

I'd like to understand how we can validate the record's attribute prior to this exception being raised.  If I add something like this:
```
  EMBEDDING_DIMENSIONS = 768
  validate do
    unless self.embedding&.count == EMBEDDING_DIMENSIONS
      errors.add(:embedding, "must contain exactly #{EMBEDDING_DIMENSIONS} dimensions, not #{self.embedding&.count.to_i}")
    end
  end
```
it doesn't help, because calling the embedding method attempts to cast the value to the Array it still triggers the Neighbor::Error.  I'm not sure how to access the value that was passed when the instance was initialized without attempting to cast and raise this error?

Is there a better way to deal with the case of invalid dimensions on the vector? 

Thanks in advance!

**Comment by ankane** [comment]
Hi @moracca, I've updated the dimensions check to use Active Record validations in the commit above.
