### ISSUE TITLE
Using halfvec

### ISSUE THREAD

**Issue by bgvo** [ankane/neighbor#21]
Thank you, @ankane, and everyone else who contributed to Neighbor. It is great. Thank you! 🙏🏻 

OpenAI returns a 3072 vector by default. It seems vector supports up to 2000 dimensions. However, I defined the embedding column as vector and it is holding the 3072 dimensions. Is the vector type being mapped to the right pgvector type behind the scenes. My other guess is that it will store the vector but will only have 2000 dimensions when indexing and/or using some functions. 

Can you please help me understand this? If I'm storing 3072 vectors, what type should I define my activerecord column? `vector` or `halfvec`.

Thank you!

**Comment by ankane** [comment]
Hi @bgvo, the `vector` type supports up to 16,000 dimensions, but you'll get an error if you try to create an index on a column with more than 2,000. You'll likely want to use `halfvec` for 3,072 dimensions (and Neighbor 0.4.0+).
