### ISSUE TITLE
Bug with neighbor_distance

### ISSUE THREAD

**Issue by espenbff** [ankane/neighbor#22]
Hi, 
When using cosine distance it seems that the neighbor_distance calculated is inverted for what I expect it to be.
For the closest embedding hits I get lower neighbor_distance values (nearer to zero).
While the embeddings which match less get higher values (nearer to one).

I stumbled upon this when I was trying to implement a threshold implementation.
The first x results does return the best hits. 

Example(in Norwegian):
Query= '"Hearing aids?"

Text1: "Mor har redusert hørsel. Kan lyd justeres opp?" (Mother has reduced hearing. Can the sound be adjusted up?)
neighbor_distance1: 0.3692709615609333

Text2: "Tilgang til opplastede bilder via enkel meny på" (Access to uploaded images via a simple menu on)
neighbor_distance2: 0.7119513366207877

The scope code I am using:

```
scope :nearest_neighbors, lambda { |embedding, distance: :cosine|
    joins(:embedding)
      .merge(Embedding.nearest_neighbors(:embedding, embedding, distance:))
  }

```

**Comment by ankane** [comment]
Hi @espenbff, it returns the cosine distance (use `1 - cosine distance` to get the cosine similarity).

**Comment by espenbff** [comment]
Aha, that makes sense. My bad.
Thanks for quick response!
