### ISSUE TITLE
missing keyword: :distance

### ISSUE THREAD

**Issue by rkiller** [ankane/neighbor#9]
Ruby 3.2.2

I can't get past this error: missing keyword: :distance when calling .nearest_neighbors(:embeddings, distance: "euclidean")

Not sure whether it's my setup or what is going on...

Thanks in advance for any help.

**Comment by ankane** [comment]
Hi @rkiller, I'm not sure how to reproduce. Can you paste the code and stack trace?

**Comment by rkiller** [comment]
I can't find documentation on it but I don't think named parameters are supported in scopes in Rails 6.1

**Comment by ankane** [comment]
The tests all pass with Rails 6.1, so I don't think there's an issue with the project.
